name: AdminHelper
version: Aplha0.1
main: mc.adminhelper.adminhelper.AdminHelper
api-version: [ 1.12.2, 1.17.1 ]
authors: [ XieXiLin ]
commands:
  cakemc:
    description: CakeMC 主命令 Help
  getop:
    description: CakeMC 获取op